# AEGIS-X PRIME — diarization WORKER environment setup (isolated).
#
# Creates a SEPARATE Python 3.12 environment outside the OneDrive repository
# containing pyannote.audio 4 + numpy 2. This must never be installed into the
# main .venv, which pins numpy<2 for ClearVoice.
# See docs/DIARIZATION_RUNTIME_ARCHITECTURE.md.
#
# Downloads packages only. NO model weights are downloaded here.
#
#   ./setup_diarization.ps1              # create/refresh the worker env
#   ./setup_diarization.ps1 -Recreate    # delete and rebuild it first

param([switch]$Recreate)

$ErrorActionPreference = "Stop"

$WorkerRoot = Join-Path $env:LOCALAPPDATA "AegisXPrime\envs\diarization"
$RepoRoot   = $PSScriptRoot

Write-Host "== AEGIS-X diarization worker environment ==" -ForegroundColor Cyan
Write-Host "target: $WorkerRoot"

if ($WorkerRoot -like "*OneDrive*") {
    Write-Error "Refusing to create the worker environment inside a OneDrive path."
    exit 1
}

# --- 1. locate and verify standard CPython 3.12 -----------------------------
$candidates = @(
    "$env:LOCALAPPDATA\Programs\Python\Python312\python.exe",
    "$env:LOCALAPPDATA\Programs\Python\Python311\python.exe"
)
$base = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $base) {
    Write-Error "No standard CPython 3.11/3.12 found. Install one from python.org first."
    exit 1
}
$ver = & $base -c "import sys; print('%d.%d' % sys.version_info[:2])"
if ($ver -ne "3.12" -and $ver -ne "3.11") {
    Write-Error "Base interpreter reports $ver; 3.12 (or 3.11) is required."
    exit 1
}
Write-Host "base interpreter: $base (Python $ver)" -ForegroundColor Green

# --- 2. create the environment ---------------------------------------------
if ($Recreate -and (Test-Path $WorkerRoot)) {
    Write-Host "Removing existing worker environment ..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force $WorkerRoot
}
if (-not (Test-Path $WorkerRoot)) {
    New-Item -ItemType Directory -Force -Path (Split-Path $WorkerRoot) | Out-Null
    & $base -m venv $WorkerRoot
}
$py = Join-Path $WorkerRoot "Scripts\python.exe"
if (-not (Test-Path $py)) { Write-Error "worker interpreter missing at $py"; exit 1 }
& $py -m pip install --upgrade pip --quiet

# --- 3. pinned cu128 PyTorch family ----------------------------------------
Write-Host "== Installing pinned PyTorch (cu128) ==" -ForegroundColor Cyan
# torchvision is intentionally NOT installed: pyannote 4 does not require it.
& $py -m pip install "torch==2.11.0" "torchaudio==2.11.0" `
    --index-url https://download.pytorch.org/whl/cu128
if ($LASTEXITCODE -ne 0) { Write-Error "torch install failed"; exit 1 }

# --- 4. pinned pyannote 4 dependency set ------------------------------------
Write-Host "== Installing pinned diarization stack ==" -ForegroundColor Cyan
& $py -m pip install -r (Join-Path $RepoRoot "requirements-diarization.txt")
if ($LASTEXITCODE -ne 0) { Write-Error "diarization stack install failed"; exit 1 }

# --- 5. lock file ------------------------------------------------------------
$lock = Join-Path $RepoRoot "requirements-diarization.lock.txt"
Write-Host "== Writing lock: $lock ==" -ForegroundColor Cyan
"# Diarization WORKER lock - generated by setup_diarization.ps1" | Out-File -Encoding utf8 $lock
"# Interpreter: Python $ver | torch/torchaudio from the cu128 index" | Out-File -Encoding utf8 -Append $lock
"# Do NOT install into the main .venv (numpy 2 breaks ClearVoice)." | Out-File -Encoding utf8 -Append $lock
& $py -m pip freeze | Out-File -Encoding utf8 -Append $lock

# --- 6. resolver integrity ---------------------------------------------------
Write-Host "== pip check ==" -ForegroundColor Cyan
& $py -m pip check
if ($LASTEXITCODE -ne 0) {
    Write-Error "pip check FAILED in the worker environment - stopping loudly."
    exit 1
}

# --- 7/8. imports + GPU compatibility (no model weights) --------------------
Write-Host "== Verifying imports and GPU compatibility (no downloads) ==" -ForegroundColor Cyan
& $py (Join-Path $RepoRoot "workers\diarization_worker\selftest.py")
if ($LASTEXITCODE -ne 0) {
    Write-Error "worker self-test FAILED - stopping loudly."
    exit 1
}

Write-Host ""
Write-Host "Diarization worker environment ready:" -ForegroundColor Green
Write-Host "  $py" -ForegroundColor Green
Write-Host "Run 'python -m aegis doctor' from the main env to see both environments." -ForegroundColor Green
